version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t dotcorereactappsample:latest .
      - docker tag dotcorereactappsample:latest 001044962630.dkr.ecr.us-east-2.amazonaws.com/dotcorereactappsample:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 001044962630.dkr.ecr.us-east-2.amazonaws.com/dotcorereactappsample:latest
      - printf '[{"imageUri": "%s"}]' 001044962630.dkr.ecr.us-east-2.amazonaws.com/dotcorereactappsample:latest > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files: imagedefinitions.json
